authapp/urls.py
from django.urls import path

# from authapp.views import login, register, profile, new_logout
from authapp.views import LoginListView, RegisterListView, ProfileFormView, new_logout,RegisterListView

app_name = 'authapp'

urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('new-logout/', new_logout, name='new_logout'),
    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify'),

]

basketapp/urls.py
from django.urls import path
from basketapp.views import basket_add,basket_delete,basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-delete/<int:id>/', basket_delete, name='basket_delete'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),


]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

# from mainapp.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('<int:category_id>/', products, name='product'),
    path('page/<int:page>/', products, name='page'),
]

mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    description = models.TextField(blank=True)
    name = models.CharField(max_length=128, unique=True)

    class Meta:
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=128, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', blank=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)  # PROTECT
    status_buy = models.CharField(max_length=64, default='Отправить в корзину')

    #
    # def __str__(self):
    #     return f'{self.name} | {self.category.name}'
    def __str__(self):
        return self.name

mainapp/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from mainapp.models import  ProductCategory,Product

# функцияя = вьюхи = контролеры.
def index(request):
    context = {
        'title': 'GeekShop',
        'header': 'Добро пожаловать',
        'username': 'Иванов Иван',
    }
    return render(request, 'mainapp/index.html', context)


def products(request,category_id=None,page=1):

    context = {
        'title': 'GeeKshop',
        'header': 'Каталог',
        'menu': ProductCategory.objects.all(),
        'carousel': [
            {'name': 'First slide', 'way': 'slide-1.jpg', 'starter': True},
            {'name': 'Second slide', 'way': 'slide-2.jpg'},
            {'name': 'Third slide', 'way': 'slide-3.jpg'},
        ],
        # 'product': Product.objects.all()

    }
    if category_id:
        products = Product.objects.filter(category_id = category_id).order_by('name')
    else:
        products = Product.objects.all().order_by('name')
    paginator = Paginator(products, per_page=3)
    products_paginator = paginator.page(page)
    context.update({'product':products_paginator})
    return render(request, 'mainapp/products.html', context)


#

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}
    {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}"> GeekShop </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:profile' %}">{{ user.first_name }} <i
                                class="fas fa-user-circle"></i></a>
                    </li>
                    {% if user.is_staff or user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_staff:index' %}">
                                <i class="fas fa-users-cog"></i></a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:new_logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/basket.js' %}"></script>

</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html'%}
{% load static %}

<!-- Custom styles for this template -->
  {% block css %}
        <link href="{% static 'css/index.css'%}" rel="stylesheet">
  {% endblock %}

<!-- Page Content -->
 {% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
 {% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel=" stylesheet">
{% endblock %}

{% block content %}

    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for i in menu %}
                        <a href="{% url 'mainapp:product' i.id %}" class="list-group-item">{{ i.name }}</a>
                    {% endfor %}
                    <!--                <a href="#" class="list-group-item">Новинки</a>-->
                    <!--                <a href="#" class="list-group-item">Одежда</a>-->
                    <!--                <a href="#" class="list-group-item">Обувь</a>-->
                    <!--                <a href="#" class="list-group-item">Аксессуары</a>-->
                    <!--                <a href="#" class="list-group-item">Подарки</a>-->

                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">

                        {% for i in carousel %}
                            {% if i.starter %}
                                <div class="carousel-item active">
                                    <img class="d-block img-fluid" src="{% static 'vendor/img/slides/'|add:i.way %}"
                                         alt="{{ i.name }}">
                                </div>
                            {% else %}
                                <div class="carousel-item">
                                    <img class="d-block img-fluid" src="{% static 'vendor/img/slides/'|add:i.way %}"
                                         alt=" {{ i.name }}">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% for i in product %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="/media/{{ i.image }}"
                                            {#                                         src="{% static 'vendor/img/products/'|add:i.way %}"#}
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href={% url 'products:product' i.id %}>{{ i.name }}</a>
                                    </h4>
                                    <h5>{{ i.price }} руб </h5>
                                    <p class="card-text">{{ i.short_description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'baskets:basket_add' i.id %}">
                                        <button type="button" class="btn btn-outline-success">Отправить в корзину
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">

                        <li class="page-item {% if not product.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if product.has_previous %} {% url 'products:page' product.previous_page_number %} {% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% for page in product.paginator.page_range %}
                            <li class="page-item"><a class="page-link"
                                                     href="{% url 'products:page' page %}">{{ page }}</a></li>
                        {% endfor %}

                        <li class="page-item {% if not product.has_next %} disable {% endif %}">
                            <a class="page-link"
                               href=" {% if product.has_next %} {% url 'products:page' product.next_page_number %} {% else %} # {% endif %}"
                            >Next</a>
                        </li>
                    </ul>
                </nav>

            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}